backend:
  name: github
  repo: "thexaib/theXaib.github.io.source"
  branch: master
  site_domain: "thexaibgithubio.netlify.app"
media_folder: "assets/uploads/images" # Folder where user uploaded files should go
public_folder: "/uploads/images"
editor:
  preview: true
collections:
  - name: "apps" # Used in routes, e.g., /admin/collections/post
    label: "Apps" # Used in the UI
    label_singular: "App"
    folder: "content/apps" # The path to the folder where the documents are stored
    path: "{{year}}-{{slug}}/index"
    preview_path: "apps/{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Featured Image", name: "image", widget: "image", choose_url: "true" , required: false}
      - { label: "Layout", name: "layout", widget: "select", add_to_top: true, allow_add: false, options: [ "simple","single" ], default:  "simple"  }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Show Author", name: "showAuthor", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    label_singular: "Post"
    folder: "content/posts" # The path to the folder where the documents are stored
    preview_path: "posts/{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "featured_image", widget: "image" , choose_url: "true" , required: false}
      - { label: "Layout", name: "layout", widget: "select", add_to_top: true, allow_add: false, options: [ "simple","single" ], default: "simple"  }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" , default: true}
      - { label: "Show Author", name: "showAuthor", widget: "boolean", default: false }
      - { label: "Categories", name: "categories", widget: "select",  multiple: true,  allow_add: true, options: [ "Mini Apps","Videos","Portfolio","News","Article" ], required: false }
      - { label: "Tags", name: "tags", widget: "select", multiple: true, allow_add: true, options: [ "English","Urdu" ] , required: false}
      - { label: "Body", name: "body", widget: "markdown" }
