backend:
  name: github
  repo: "thexaib/theXaib.github.io.source"
  branch: master
  site_domain: "thexaibgithubio.netlify.app"
media_folder: "assets/uploads/images" # Folder where user uploaded files should go
public_folder: "/uploads/images"
collections:
  - name: "apps" # Used in routes, e.g., /admin/collections/post
    label: "Apps" # Used in the UI
    folder: "content/apps" # The path to the folder where the documents are stored
    path: "{{year}}-{{slug}}/index"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
